### PR TITLE
update project name and url path to news-site

### PR DESCRIPTION
**Pull request by ekulbyrnes**

### CODE REVIEW

**Comment by mattcen** [comment]
`s/-/_/g`; Python modules can't contain dashes in their names.

kthxbai

**Review by ekulbyrnes — COMMENTED** [review]
updated name to fix naming errors

**Comment by mattcen** [comment]
try agian

**Comment by mattcen** [comment]
LGTM. I recommend "squash and merge" rather than just "merge pull request" to tidy up all the intermediate fixup commits.

**Pull request closed without merging**
